# -*- coding: utf-8 -*-
"""07.07.02 Exercícios Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-7w6uZza1l-gkiU_nn-K0VJ6n-aoFQ

# Exercícios

## 1. Faturamento do Melhor e do Pior Mês do Ano

Qual foi o valor de vendas do melhor mês do Ano?
E valor do pior mês do ano?
"""
"""## 2. Continuação

Agora relacione as duas listas para printar 'O melhor mês do ano foi {} com {} vendas' e o mesmo para o pior mês do ano.

Calcule também o faturamento total do Ano e quanto que o melhor mês representou do faturamento total.

Obs: Para o faturamento total, pode usar a função sum(lista) que soma todos os itens de uma lista
"""
"""## 3. Crie uma lista com o top 3 valores de vendas do ano (sem fazer "no olho")

Dica: o método remove retira um item da lista.
"""

meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 20120, 17540, 15555, 49051, 9650]

vendas_1sem.extend(vendas_2sem)
maior_valor = max(vendas_1sem)
menor_valor = min(vendas_1sem)

i_maior_valor = vendas_1sem.index(maior_valor)
i_menor_valor = vendas_1sem.index(menor_valor)

print('O mes de {} foi o melhor mes do ano, com {} vendas! '.format(meses[i_maior_valor], maior_valor))
print('O mes de {} foi o pior mes do ano, com {} vendas! '.format(meses[i_menor_valor], menor_valor))

ft_total = sum(vendas_1sem)
percentual = (maior_valor / ft_total) * 100
print(r"O faturamento total do ano foi de R$ {}! Com o melhor mes representando {:.2f}% do faturamento total!".format(ft_total, percentual))

top3 = sorted(vendas_1sem, reverse=True)[:3]
print(f"Top 1 - {top3[0]}\nTop 2 - {top3[1]}\nTop 3 - {top3[2]}")